//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace text
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_table
    {
        public decimal ID { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> zip { get; set; }
        public string hobbies { get; set; }
    }
}
